name: sentinel
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - ipykernel=5.3.4
  - pandas=1.1.1
  - python=3.7.7
  - pytorch=1.6.0
  - scikit-learn=0.23.1
  - spacy=2.3.1
  - tqdm=4.48.2
  - nb_conda_kernels
  - pip:
    - simpletransformers==0.47.3
    - wandb==0.9.5
